version: 2.1
orbs:
  jq: circleci/jq@2.2.0

jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - jq/install
      - run: git submodule sync
      - run: git submodule update --init
      - run: |
          URL=$(wget -O - https://ziglang.org/download/index.json | jq -r '.master."'$(arch)'-linux".tarball' 2>&1)
          wget $URL
          tar xf $(basename $URL) -C "$HOME"
          export PATH=$PATH:$HOME/$(basename -s .tar.xz $URL)
          zig build test
          zig build bench

workflows:
  version: 2
  test:
    jobs:
      - test